---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: conftest-clair
spec:
  results:
    - name: HACBS_TEST_OUTPUT
      description: test output
  steps:
    - name: conftest-vulnerabilities
      image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        /usr/bin/conftest test --no-fail $(workspaces.workspace.path)/clair-result.json \
        --policy /project/clair/vulnerabilities-check.rego --namespace required_checks \
        --output=json | tee $(workspaces.workspace.path)/clair-vulnerabilities.json
    - name: test-format-result
      image: quay.io/redhat-appstudio/hacbs-test:stable
      script: |
        HACBS_ERROR_OUTPUT=$(jq -rc --arg date $(date +%s) --null-input \
          '{result: "ERROR", timestamp: $date}')
        HACBS_TEST_OUTPUT=$(jq -rce --arg date $(date +%s) \
          '.[] | { result: (if (.failures | length > 0) then "FAILURE" else "SUCCESS" end),
                   timestamp: $date,
                   namespace,
                   successes,
                   failures: (.failures // [])|map(.metadata.details.name)
                 }' $(workspaces.workspace.path)/clair-vulnerabilities.json || true)
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
  workspaces:
    - name: workspace